### ISSUE TITLE
3 gang Moes switch showing up as 1 gang

### ISSUE THREAD

**Issue by Echoes675** [martinkura-svk/Hubitat#1]
https://github.com/martinkura-svk/Hubitat/blob/fa9780e3ef51a29f100d079de4a39a987c6807e5/Moes%20ZigBee%20Wall%20Switch#L208

_TZE200_tz32mtza is listed in both the case for 1 button switch and the 3 button switch. Should just be a 3 button switch

**Comment by kkossev** [comment]
Thank you for the bug report!
The repository code is now updated to revision 1.04 - 2022-10-12 - _TZE200_tz32mtza bug fix; code cleanup
